"""user roles and permissions 

Revision ID: 006af5604377
Revises: c14d6429a69c
Create Date: 2018-03-12 22:36:31.685495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006af5604377'
down_revision = 'c14d6429a69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
