"""add hash for User

Revision ID: 274368ec2cf6
Revises: aae055bb2c55
Create Date: 2018-03-09 12:11:57.007572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274368ec2cf6'
down_revision = 'aae055bb2c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
