"""add user's school

Revision ID: aae055bb2c55
Revises: 
Create Date: 2018-03-08 18:26:17.619779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae055bb2c55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_school'), 'users', ['school'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_school'), table_name='users')
    op.drop_column('users', 'school')
    # ### end Alembic commands ###
